[application]

# App (Project) Name
name = "elk-bledom-gui"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

# Spécifier le chemin du template HTML
html_template = "index.html"  # Le fichier doit être à la racine du projet

[web.app]

# HTML title tag content
title = "ELK BLEDOM GUI"
html_template = "index.html"  # Ajoutez cette ligne ici

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]
